experiment_name: "hessian_mnist_var_reg_5f"
device: "auto"

data:
  dataset_name: "mnist"  
  root: "/srv/local/data"
  batch_size: 128

model:
  type: 'mnist'
  hidden_dim: 256

training:
  epochs: 5
  lr: 0.01
  momentum: 0.9
  seed: 0

analysis:
  method: 'fisher'
  use_exact_hessian: true
  num_power_iters: 50
  reg: [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]

remove:
  enabled: false
  num_samples_to_test: 1